# If a file in layer dir changed lable PR with code tag
core:
- 'core/**/*'

checkout:
- 'checkout/**'

firesale:
- 'firesale/**'

# If any file under design or its sub dirs is chagned append the design lable
doc:
- 'docs/**'
- '**/*.md'

# TODO: fix paths when coding starts
model:
- '**/model.py'
- '**/model/**'
urls:
- '**/urls.py'
- '**/urls/**'
view:
- '**/view.py'
- '**/view/**'

# all dotfiles, all files in dotdirs, and all .md files in root
meta:
- '.*/**/*'
- '.*'

# changes to any file in dir called test or its subdirs
tests:
- '**/tests/**/*'
