# If a file in layer dir changed lable PR with code tag
code:
- 'FireBase!/**/*'
- 'db/**/*'

# If any file under design or its sub dirs is chagned append the design lable
doc:
- 'docs/**/*'

# TODO: fix paths when coding starts
api:
- 'firebase/**/*'
db:
- 'db/**/*'
web:
- 'firebase/**/*'

# all dotfiles, all files in dotdirs, and all .md files in root
meta:
- '.*/**/*'
- '.*'
- '*.md'

tests:
- 'tests/**/*'
