# If a file in layer dir changed lable PR with code tag
code:
- 'layers/**/*'

# If any file under design or its sub dirs is chagned append the design lable
doc:
- 'docs/**/*'

api:
- 'layers/api/**/*'
db:
- 'layers/db/**/*'
web:
- 'layers/web/**/*'

# all dotfiles, all files in dotdirs, and all .md files in root
meta:
- '.*/**/*'
- '.*'
- '*.md'

tests:
- '**/*/tests/**/*'
