version: "3.9"

services:
    traefik:
        image: "traefik:v2.6"
        container_name: "traefik"
        command:
            #- "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:80
        volumes:
            - .:/code
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.web.rule=Host(`fire-sale.deals`)"
            - "traefik.http.services.web.loadbalancer.server.port=80"
            - "traefik.http.routers.web.entrypoints=web"
