# Generated by Django 4.0.4 on 2022-05-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbids',
            name='status',
            field=models.CharField(choices=[('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('PENDING', 'Pending')], default='PENDING', max_length=128),
        ),
    ]
