# Generated by Django 4.0.4 on 2022-05-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userbids_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbids",
            name="status",
            field=models.CharField(
                choices=[
                    ("REJECTED", "Rejected"),
                    ("ACCEPTED", "Accepted"),
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=128,
            ),
        ),
    ]
