# Generated by Django 4.0.4 on 2022-05-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_item_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbids",
            name="expires",
            field=models.DateTimeField(blank=True),
        ),
    ]
