# Generated by Django 4.0.4 on 2022-05-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_userbids_expires"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="profile",
            table="core_profile",
        ),
    ]
